### ISSUE TITLE
Make SRIOV VFs to push/pop tags like vlan or vxlan

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-sriov#489]
We need to rework  SRIOV VFs looking at experience with vlan and vxlan push/pop tags mechanic. See at https://github.com/networkservicemesh/sdk-kernel/pulls?q=is%3Apr+is%3Aclosed+vlan+

**Comment by glazychev-art** [comment]
@edwarnicke 
Do I understand correctly that we need to implement a feature that allows to send VLAN-tagged traffic by virtual functions (VF)?

We currently only have one VLAN on the Packet cluster, which we configure when the server starts. And the server's network configuration does not need to be VLAN-aware (see https://deploy.equinix.com/developers/docs/metal/layer2-networking/layer2-mode/#server-configuration-unbonded).

For this feature, we need to explicitly tag the traffic. Am I right?

**Comment by glazychev-art** [comment]
Current state:
1. Solved the problem with the VLAN on the packet. (for unknown reasons, at least 2 VLANs must be used)
2. Manually configured [SriovKernel2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/SriovKernel2Noop) example with tagged VF.
3. [In progress] Manual configuring [Vfio2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Vfio2Noop)

Unresolved issues:
1. Should we consider adding a new application? For example, [remotevlan](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/remotevlan) has [cmd-nse-remote-vlan](https://github.com/networkservicemesh/cmd-nse-remote-vlan) that configures `gw` and `vlan`. But our current [SriovKernel2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/SriovKernel2Noop) doesn't have something similar, we use simple cmd-nse-icmp-responder.
2. Should we reuse the current chain elements for configuration? For example, [ethernetcontext](https://github.com/networkservicemesh/sdk-kernel/tree/main/pkg/kernel/networkservice/ethernetcontext) is very similar what we need.
3. Calico CNI plugin (**_not_** VPP) on kubernetes cluster may stop working after manipulating vlan/ip addresses. Need to test more. 
4. Because we will now assign VLANs in deployment-k8s (in the endpoint configuration), there is a problem of VLANs overlapping when running a default and Calico-VPP clusters at the same time. These tests from **different clusters** will affect each other.

**Comment by glazychev-art** [comment]
Current state:
1. Run [Vfio2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Vfio2Noop) example with vlan tagged VFs.

**Question:**
When we use VLAN tags, we set them in the NSE config. For example:
- Remote VLAN - https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/remotevlan/patch-nse.yaml
```
metadata:
  name: nse-remote-vlan
  ...
            - name: NSM_SERVICES
              value: "finance-bridge { vlan: 100; via: gw1}"
```
- Vfio2Noop will look like:
```
metadata:
  name: nse-vfio
  ...
            - name: NSM_SERVICE_NAMES
              value: "vfio2noop@worker.domain: { addr: 0a:55:44:33:22:11; vlan: 1044 }"
```
They use [cmd-nse-remote-vlan](https://github.com/networkservicemesh/cmd-nse-remote-vlan) and [cmd-nse-vfio](https://github.com/networkservicemesh/cmd-nse-vfio) which parse the config.

The point is that for [SriovKernel2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/SriovKernel2Noop) we need something similar because it uses a simple **cmd-nse-icmp-responder**. Should we add a new application, or modify existing ones? Perhaps we need to consider [cmd-nse-vlan-vpp](https://github.com/networkservicemesh/cmd-nse-vlan-vpp)?

@denis-tingaikin @edwarnicke 
Any thoughts would be helpful!

**Comment by glazychev-art** [comment]
What else needs to be done on this issue:
1. Merge prepared PRs (see above)
2. Create a new or modify existing NSE app (see https://github.com/networkservicemesh/sdk-sriov/issues/489#issuecomment-1427930888)
3. Modify our deployment-k8s example (most of it is already done locally)
4. Modify integration-k8s-packet setup (most of it is already done locally)
5. Testing

**Comment by glazychev-art** [comment]
**Vlan tagged Vfio2Noop example**

NSC config:
```
metadata:
  name: nsc-vfio
  ...
            - name: NSM_NETWORK_SERVICES
              value: vfio://vfio2noop?sriovToken=worker.domain/10G
```

NSE config:
```
metadata:
  name: nse-vfio
  ...
            - name: NSM_SERVICE_NAMES
              value: "vfio2noop@worker.domain: { vlan: 1044 }"
```
![vfio-noop](https://user-images.githubusercontent.com/17748275/225916465-1cce30a0-d407-471c-b071-14b5c28b234a.svg)
1. NSC sends a request that reaches the NSE
2. NSE adds vlan-tag from configuration to the ethernet_context. It also runs a bash script to configure the interface (because of NOOP mechanism)
3. Forwarder-1 adds vlan-tag 1044 to the VF using `netlink` on the way back (see [ethernetcontext](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/ethernetcontext/vf_common.go#L124))

@edwarnicke 
Could you take a look? Is this diagram correct for [Vfio2Noop](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Vfio2Noop)?
